### PR TITLE
Set WM_CLASS and _NET_WM_STATE

### PR DESCRIPTION
**Pull request by cecilialau6776**
- Set `WM_CLASS` to `"lazybar", "Lazybar"`
- Set `_NET_WM_STATE` to `_NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE`

### CODE REVIEW

**Comment by Qelxiros** [comment]
According to [the EWMH spec](https://specifications.freedesktop.org/wm-spec/latest), `_NET_WM_NAME` should be used over `WM_NAME`, and `_NET_WM_STATE_ABOVE` should not be used by applications. I'm not sure about `_NET_WM_STATE_STICKY`, but it feels like it should be covered by `_NET_WM_WINDOW_TYPE(_DOCK)`. I'm going to close this for now, but I've opened #5, so I'll come back to this eventually.

**Comment by cecilialau6776** [comment]
What about `WM_CLASS`?

**Comment by Qelxiros** [comment]
`WM_CLASS` comes from ICCCM, which lazybar currently doesn't support. I may add it in the future, but I use i3, which doesn't appear to be ICCCM-compliant, which might make testing more difficult.

**Comment by Qelxiros** [comment]
Turns out I didn't know what ICCCM was. These changes were (approximately) implemented in 14d796d.

**Pull request closed without merging**
